# Generated by Django 5.2.5 on 2025-08-26 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studyapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='notes',
            field=models.TextField(blank=True, default=''),
        ),
    ]
